a = input(f'Digite algo: ')
print(f'O tipo primitivo desse valor é {type(a)}')
print(f'Só tem espaços? {a.isspace()}')
print(f'É um número? {a.isnumeric()}')
print(f'É alfabético? {a.isalpha()}')
print(f'Está em maíscula? {a.isupper()}')
print(f'Está em minúcula? {a.islower()}')
print(f'Está capitalizada? {a.istitle()}')
